const ACTION_TYPES = {
  TOGGLE_POSTS_LOADING: 'TOGGLE_POSTS_LOADING',
  RECEIVE_POSTS: 'RECEIVE_POSTS',
  RESET_POSTS: 'RESET_POSTS',
  REFRESH_POSTS: 'REFRESH_POSTS',
  RECEIVE_ENTRIES: 'RECEIVE_ENTRIES',
  REFRESH_ENTRIES: 'REFRESH_ENTRIES',
  TOGGLE_ENTRIES_LOADING: 'TOGGLE_ENTRIES_LOADING',
  RECEIVE_MY_ENTRIES: 'RECEIVE_MY_ENTRIES',
  REFRESH_MY_ENTRIES: 'REFRESH_MY_ENTRIES',
  TOGGLE_MY_ENTRIES_LOADING: 'TOGGLE_MY_ENTRIES_LOADING',
  TOGGLE_TOKEN: 'TOGGLE_TOKEN',
  TOGGLE_USER_LOADING: 'TOGGLE_USER_LOADING',
  REFRESH_USER: 'REFRESH_USER',
};

export default ACTION_TYPES;
