const ACTION_TYPES = {
  TOGGLE_POSTS_LOADING: 'TOGGLE_POSTS_LOADING',
  RECEIVE_POSTS: 'RECEIVE_POSTS',
  RESET_POSTS: 'RESET_POSTS',
  REFRESH_POSTS: 'REFRESH_POSTS',
  RECEIVE_ENTRIES: 'RECEIVE_ENTRIES',
  REFRESH_ENTRIES: 'REFRESH_ENTRIES',
  TOGGLE_ENTRIES_LOADING: 'TOGGLE_ENTRIES_LOADING',
};

export default ACTION_TYPES;
