const ACTION_TYPES = {
  TOGGLE_POSTS_LOADING: 'TOGGLE_POSTS_LOADING',
  RECEIVE_POSTS: 'RECEIVE_POSTS',
  RESET_POSTS: 'RESET_POSTS',
  REFRESH_POSTS: 'REFRESH_POSTS',
  RECEIVE_ENTRANCES: 'RECEIVE_ENTRANCES',
  REFRESH_ENTRANCES: 'REFRESH_ENTRANCES',
  TOGGLE_ENTRANCES_LOADING: 'TOGGLE_ENTRANCES_LOADING'
};

export default ACTION_TYPES;
